In [ ]:
https://medium.com/@shammypratap/tensorflow-for-natural-language-processing-nlp-a702ff95d330
https://www.scaler.com/topics/tensorflow/tensorflow-word-embeddings/

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import tensorflow as tf

# Sample text data
texts = ["This is a simple example of text preprocessing using TensorFlow.",
         "TextVectorization is a powerful tool for NLP tasks.",
         "It can handle tokenization, lowercasing, and padding with ease!"]


In [ ]:

# Create a TextVectorization layer
vectorizer = tf.keras.layers.TextVectorization(max_tokens=100, output_mode='int', output_sequence_length=10)

# Adapt the layer to the text data
vectorizer.adapt(texts)

# Tokenize and preprocess the text data
processed_data = vectorizer(texts)

# Get the vocabulary and tokenized sequences
vocabulary = vectorizer.get_vocabulary()
tokenized_sequences = processed_data.numpy()

# Print the processed data, vocabulary, and tokenized sequences
print("Processed Data:")
print(processed_data)

print("\nVocabulary:")
print(vocabulary)

print("\nTokenized Sequences:")
print(tokenized_sequences)

Processed Data:
tf.Tensor(
[[ 8  2  3 13 23 17 10 14  5 11]
 [ 9  2  3 15  6 22 18 12  0  0]
 [20 25 21  7 19 26 16  4 24  0]], shape=(3, 10), dtype=int64)

Vocabulary:
['', '[UNK]', 'is', 'a', 'with', 'using', 'tool', 'tokenization', 'this', 'textvectorization', 'text', 'tensorflow', 'tasks', 'simple', 'preprocessing', 'powerful', 'padding', 'of', 'nlp', 'lowercasing', 'it', 'handle', 'for', 'example', 'ease', 'can', 'and']

Tokenized Sequences:
[[ 8  2  3 13 23 17 10 14  5 11]
 [ 9  2  3 15  6 22 18 12  0  0]
 [20 25 21  7 19 26 16  4 24  0]]


# Embeddings


![](https://github.com/carabedo/labs/blob/master/img/rnn_emb.png?raw=true)



https://nlp.stanford.edu/projects/glove/

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2024-09-05 00:43:17--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-09-05 00:43:18--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip         62%[===========>        ] 514.58M  5.01MB/s    eta 59s    ^C


In [ ]:
!unzip glove.6B.zip

Archive:  glove.6B.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of glove.6B.zip or
        glove.6B.zip.zip, and cannot find glove.6B.zip.ZIP, period.


In [ ]:
import tensorflow as tf
import numpy as np

# Path to the GloVe embeddings file
glove_file = 'glove.6B.50d.txt'

# Load the GloVe embeddings into a dictionary
embeddings_index = {}
with open(glove_file, 'r', encoding='utf-8') as file:
    for line in file:
        values = line.split()
        word = values[0]
        vector = np.array(values[1:], dtype='float32')
        embeddings_index[word] = vector

# Sample words to look up in the GloVe embeddings
sample_words = ['king', 'queen', 'apple', 'banana']

# Create an embedding matrix for the sample words
embedding_dim = len(embeddings_index['king'])
embedding_matrix = np.zeros((len(sample_words), embedding_dim))

for i, word in enumerate(sample_words):
    if word in embeddings_index:
        embedding_matrix[i] = embeddings_index[word]

# Define a Keras embedding layer using the GloVe embeddings
embedding_layer = tf.keras.layers.Embedding(
    len(sample_words),
    embedding_dim,
    weights=[embedding_matrix],
    trainable=False  # Set to True to fine-tune the embeddings
)


FileNotFoundError: [Errno 2] No such file or directory: 'glove.6B.50d.txt'

In [ ]:

# Example usage of the embedding layer
input_data = [sample_words.index(word) for word in sample_words]

# Convert the list to a tensor
input_tensor = tf.constant(input_data)

# Pass the tensor to the embedding layer
embedded_data = embedding_layer(input_tensor)

print("Sample words:", sample_words)
print("Embedded data:", embedded_data)


Sample words: ['king', 'queen', 'apple', 'banana']
Embedded data: tf.Tensor(
[[ 0.50451    0.68607   -0.59517   -0.022801   0.60046   -0.13498
  -0.08813    0.47377   -0.61798   -0.31012   -0.076666   1.493
  -0.034189  -0.98173    0.68229    0.81722   -0.51874   -0.31503
  -0.55809    0.66421    0.1961    -0.13495   -0.11476   -0.30344
   0.41177   -2.223     -1.0756    -1.0783    -0.34354    0.33505
   1.9927    -0.04234   -0.64319    0.71125    0.49159    0.16754
   0.34344   -0.25663   -0.8523     0.1661     0.40102    1.1685
  -1.0137    -0.21585   -0.15155    0.78321   -0.91241   -1.6106
  -0.64426   -0.51042  ]
 [ 0.37854    1.8233    -1.2648    -0.1043     0.35829    0.60029
  -0.17538    0.83767   -0.056798  -0.75795    0.22681    0.98587
   0.60587   -0.31419    0.28877    0.56013   -0.77456    0.071421
  -0.5741     0.21342    0.57674    0.3868    -0.12574    0.28012
   0.28135   -1.8053    -1.0421    -0.19255   -0.55375   -0.054526
   1.5574     0.39296   -0.2475     0.3425

## Usando embedding con una LSTM

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample text data for sentiment analysis
texts = ["This is a positive review.",
         "Negative experience with this product.",
         "I love this book!"]

# Corresponding labels (0 for negative, 1 for positive)
labels = [1, 0, 1]

# Tokenize the text data
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(texts)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(texts)



# Pad sequences to have a consistent length
sequences = pad_sequences(sequences, maxlen=10, padding='post', truncating='post')

# Build an LSTM model using TensorFlow/Keras
model = keras.Sequential([
    keras.layers.Embedding(input_dim=len(word_index) + 1, output_dim=16),
    keras.layers.LSTM(64),  # LSTM layer
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



In [ ]:
# Ensure sequences and labels are TensorFlow tensors
sequences_tensor = tf.convert_to_tensor(sequences, dtype=tf.int32)  # Specify dtype if necessary
labels_tensor = tf.convert_to_tensor(labels, dtype=tf.float32)      # Or another appropriate dtype

# Check shapes (optional)
print("Sequences tensor shape:", sequences_tensor.shape)
print("Labels tensor shape:", labels_tensor.shape)

# Train the model with the tensors
model.fit(sequences_tensor, labels_tensor, epochs=50,verbose=0)


Sequences tensor shape: (3, 10)
Labels tensor shape: (3,)


In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ (None, 10, 16)              │             224 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_5 (LSTM)                        │ (None, 64)                  │          20,736 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 16)                  │           1,040 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 66,053 (258.02 KB)

 Trainable params: 22,017 (86.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 44,036 (172.02 KB)

In [ ]:

# Evaluate the model
test_texts = ["Excellent book!", "Worst experience ever."]
test_sequences = tokenizer.texts_to_sequences(test_texts)
test_sequences = pad_sequences(test_sequences, maxlen=10, padding='post', truncating='post')
test_predictions = model.predict(test_sequences)
print("Test Predictions:", test_predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step
Test Predictions: [[0.99953175]
 [0.46732506]]


# Generando texto

In [ ]:
!wget https://github.com/carabedo/labs/raw/master/data/p12_2010.txt

--2024-09-05 00:45:04--  https://github.com/carabedo/labs/raw/master/data/p12_2010.txt
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/carabedo/labs/master/data/p12_2010.txt [following]
--2024-09-05 00:45:05--  https://raw.githubusercontent.com/carabedo/labs/master/data/p12_2010.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3803210 (3.6M) [text/plain]
Saving to: ‘p12_2010.txt’

p12_2010.txt        100%[===================>]   3.63M  --.-KB/s    in 0.08s   

2024-09-05 00:45:05 (44.8 MB/s) - ‘p12_2010.txt’ saved [3803210/3803210]



In [ ]:

# Load the text file into a string
with open('/content/p12_2010.txt', 'r') as file:
    data = file.read()

# Split the string into rows based on '---'
rows = data.strip().split('---')

# Split each row into columns and store in a list
data_list = []
for row in rows:
    columns = row.strip().split('\n')
    if len(columns) == 3:
        data_list.append(columns)

# Convert the list into a DataFrame
df = pd.DataFrame(data_list, columns=['volanta', 'titulo', 'bajada'])



In [ ]:
df=df[df.volanta !='nan'].reset_index(drop=True)

In [ ]:
df

volanta  \
0                   LA VENTANA > MEDIOS Y COMUNICACIóN   
1                   LA VENTANA > MEDIOS Y COMUNICACIóN   
2                     PSICOLOGíA > ESCUELA Y AUTORIDAD   
3     EL PAíS > ROBARON DOCUMENTOS Y UNA COMPUTADOR...   
4     EL PAíS > AVALANCHA DE REPUDIOS A DIEGO GUELA...   
...                                                 ...   
8860  EL MUNDO > EL EX MANDATARIO ISRAELI MOSHE KATS...   
8861  EL MUNDO > ES EL SALDO DE TRES AÑOS DE GUERRA...   
8862  DEPORTES > UN CENTENAR DE DESTACADOS EN LA ACT...   
8863  DEPORTES > MAÑANA SE PONE EN MARCHA LA EDICIO...   
8864  PSICOLOGíA > LA PARRHESíA COMO FORMA DEL DEC...   

                                                 titulo  \
0                   Réplica y participación ciudadana   
1                       Medios y responsabilidad social   
2     Las éticas de la educación vulneradas por la...   
3                Visita de los pesados para fin de año   
4                El macrismo tiró sus propios petardos   
...                                                 ...   
8860               Un presidente culpable de violación   
8861                              Mil niños asesinados   
8862                       Los 100 deportistas del 2010   
8863                            Año Nuevo, Dakar veloz   
8864                                Coraje de la verdad   

                                                 bajada  
0     Dos referencias a la responsabilidad social de...  
1     Desde Madrid, y a partir de un estudio sobre l...  
2     La autora observa que “en cada docente se conc...  
3     La titular de la Secretaría y otras siete per...  
4     Guelar tiró la piedra el miércoles en un doc...  
...                                                 ...  
8860  En un fallo que fue destacado como ejemplar po...  
8861  Según un informe de la ONG mexicana Red por l...  
8862  Están los obvios, los que no podían faltar, ...  
8863  Con record de participantes argentinos y más ...  
8864  La parrhesía, tal como la estudió Michel Fou...  

[8865 rows x 3 columns]

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample text data for training the text generation model
texts = df.volanta.to_list()

# Tokenize the text data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
word_index = tokenizer.word_index

# Convert text data to sequences
sequences = tokenizer.texts_to_sequences(texts)

# Create input and target sequences for text generation
input_sequences = []
target_sequences = []

for sequence in sequences:
    for i in range(1, len(sequence)):
        input_sequences.append(sequence[:i])
        target_sequences.append(sequence[i])

# Pad the sequences to have a consistent length
input_sequences = pad_sequences(input_sequences)

# Build an LSTM-based text generation model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(word_index) + 1, output_dim=16),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(len(word_index) + 1, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

input_sequences_tensor = tf.convert_to_tensor(input_sequences, dtype=tf.int32)
target_sequences_tensor = tf.convert_to_tensor(target_sequences, dtype=tf.int32)


# Train the model
model.fit(input_sequences_tensor, target_sequences_tensor, epochs=10)


Epoch 1/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 172s 52ms/step - loss: 7.0067
Epoch 2/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 193s 49ms/step - loss: 5.9283
Epoch 3/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 188s 45ms/step - loss: 5.5052
Epoch 4/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 148s 45ms/step - loss: 5.1745
Epoch 5/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 157s 48ms/step - loss: 4.8382
Epoch 6/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 158s 48ms/step - loss: 4.5431
Epoch 7/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 157s 48ms/step - loss: 4.2985
Epoch 8/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 203s 48ms/step - loss: 4.0743
Epoch 9/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 200s 48ms/step - loss: 3.8573
Epoch 10/10
3274/3274 ━━━━━━━━━━━━━━━━━━━━ 157s 48ms/step - loss: 3.6735


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 29, 16)              │         201,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 64)                  │          20,736 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 12573)               │         817,245 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,117,449 (11.89 MB)

 Trainable params: 1,039,149 (3.96 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,078,300 (7.93 MB)

In [ ]:
def sample(predictions, temperature=1.0):
    predictions = np.asarray(predictions).astype('float64')
    predictions = np.log(predictions + 1e-7) / temperature
    predictions = np.exp(predictions) / np.sum(np.exp(predictions))
    return np.random.choice(len(predictions), 1, p=predictions)[0]


In [ ]:

# Generate text using the trained model
seed_text = "DEPORTES"
generated_text = seed_text
max_sequence_length=10
for _ in range(20):
    sequence = tokenizer.texts_to_sequences([generated_text])[0]

    # Pad or truncate the sequence to the expected length
    sequence = sequence[-max_sequence_length:]
    sequence = tf.keras.preprocessing.sequence.pad_sequences([sequence], maxlen=max_sequence_length)

    # Convert to tensor
    sequence_tensor = tf.convert_to_tensor(sequence, dtype=tf.int32)

    # Predict the next word's probabilities
    next_word_probs = model.predict(sequence_tensor, verbose=0)[0]

    # Sample the next word's index
    next_word_index = sample(next_word_probs, temperature=1.0)

    # Find the word corresponding to the predicted index
    next_word = [word for word, index in word_index.items() if index == next_word_index][0]

    generated_text += " " + next_word

print(generated_text)


DEPORTES el autor del fútbol de marcó del pensamiento más violada haroldo médicos provincia de represor a su informe que negociar
